#!/usr/bin/perl

use v5.24;
use warnings;
use autodie;

open my $cmd, '-|', 'stest', '-flx', split /:/, $ENV{DMENU_PATH} || $ENV{PATH};
my @programs = readline $cmd;
my %favmap = map { $_ => 1 } split /[ ,;:]/, $ENV{DMENU_FAVS} // '';

chomp @programs;
print map { "$_\n" } sort {
	if (exists $favmap{$a} == exists $favmap{$b}) {
		return $a cmp $b;
	}
	else {
		return exists $favmap{$b} <=> exists $favmap{$a};
	}
} @programs;

